-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 13-07-2023 a las 23:25:38
-- Versión del servidor: 10.4.27-MariaDB
-- Versión de PHP: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `capacitacion`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `cursos`
--

CREATE TABLE `cursos` (
  `id` int(11) NOT NULL,
  `nombre` varchar(120) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `nivel_curso` int(10) NOT NULL,
  `descripcion` varchar(1000) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `logo_curso` varchar(255) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `carga_horaria` int(10) NOT NULL,
  `fecha_inicio` date NOT NULL,
  `fecha_fin` date NOT NULL,
  `id_capacitador` int(10) NOT NULL,
  `id_modalidad` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `cursos`
--

INSERT INTO `cursos` (`id`, `nombre`, `nivel_curso`, `descripcion`, `logo_curso`, `carga_horaria`, `fecha_inicio`, `fecha_fin`, `id_capacitador`, `id_modalidad`) VALUES
(17, 'ELECTRICIDAD DEL AUTOMOTOR', 5, ' DESTINATARIOS  \r\nDestinado a personas que quieran aprender e iniciarse en el mundo de la electricidad automotora.  \r\n\r\nOBJETIVOS  Acercar los conocimientos básicos, así poder iniciar el camino a la capacitación de mayor nivel. Lograr insertarlos en el mundo laboral con conocimiento.  \r\n\r\nCONTENIDO  Modulo I • Necesidad de conocer la Teoría Atómica y principios básicos de la electricidad • Preguntas para la evaluación diagnóstica • Identificación de cómo se desarrolla la electricidad mediante la Física • ¿Qué es la electricidad? • Conocimiento y aplicación de voltaje –corriente y resistencia en la electricidad del automóvil • Conocimiento de la Teoría Atómica • Interpretación sobre cómo actúa la teoría atómica a través de reacciones químicas • Necesidad de conocer las leyes de Ohm, Kirchhoff y circuitos simples y potencia • Interpretación de las leyes de Ohm y Kirchhoff • Interpretación y aplicación de potencia • Reconocimiento e interpretación de circuitos simples • Mediciones eléctri', 'IMG-64ad8183d7af26.18317383.jpeg', 1, '2023-06-30', '2023-09-30', 13, 7),
(18, 'ELECTRÓNICA DEL AUTOMOTOR', 5, ' DESTINATARIOS\r\n Destinado a personas que quieran aprender e iniciarse en el mundo de los sistemas que componen un automotor.  \r\n\r\nOBJETIVOS Acercar los conocimientos básicos de los sistemas automotrices, así poder iniciar el camino a la capacitación de mayor nivel. Lograr insertarlos en el mundo laboral con conocimiento.  \r\n\r\nCONTENIDO • Módulo I • Medición de señales eléctricas y estructuras de control • Señales eléctricas • Preguntas para la evaluación diagnóstica • Generador de señales • Introducción • Osciloscopio • Señales analógicas y señales digitales • Sistemas electrónicos • Introducción • Estructuras de control Módulo II • Montaje de circuitos electrónicos en placa • Placas electrónicas • Preguntas para la evaluación diagnóstica • Tarjetas de circuitos impresos • Protoboard • Soldadura • Soldadura blanda • Características de una buena soldadura • Herramientas • Recomendaciones y medidas de seguridad', 'IMG-64ad8201afe187.90464063.jpg', 1, '2023-06-15', '2023-09-15', 11, 7),
(19, 'AIRE ACONDICIONADO AUTOMOTOR', 5, ' DESTINATARIOS\r\n Destinado a personas que quieran iniciarse en el mundo de la reparación de automotores, sin conocimiento previo.  \r\n\r\nOBJETIVOS Acercar los conocimientos básicos de la mecánica, así poder iniciar el camino a la capacitación de mayor nivel. Lograr insertarlos en el mundo laboral con conocimiento.  \r\n\r\nCONTENIDO • Reconocimiento inicial y visual de todos sus componentes • Compresor • Evaporador • Condensador • Cañería baja y alta • Filtros • Desarrollo individual de cada componente • Medición • Actuación • Comparación • Reconocimiento de su instalación y medición de sus componentes eléctricos • Bobina • Presostato • Termostato • Forzador • Electro ventilador • Válvulas reguladoras de presión • Relay • Cableado • Fusibles • Ecu • Comando • Lectura e interpretación de un circuito eléctrico • Presiones • Equivalencias • Formas de medición • Precauciones y seguridad de trabajo • Desarrollo y reconocimiento de herramientas de trabajo • Manipulación • Recomendación • Alternati', 'IMG-64ad82eed88412.06217888.jpeg', 1, '2023-06-10', '2023-09-10', 11, 7),
(20, 'MECÁNICA DE MOTORES NAFTEROS', 5, ' DESTINATARIOS Destinado a personas que quieran iniciarse en el mundo de la reparación de automotores, sin conocimiento previo.  \r\n\r\nOBJETIVOS Acercar los conocimientos básicos de la mecánica, así poder iniciar el camino a la capacitación de mayor nivel. Lograr insertarlos en el mundo laboral con conocimiento.  \r\n\r\nCONTENIDO Modulo I • Metrología • Metrología y mediciones • Preguntas para la evaluación diagnóstica • Precisión y exactitud • ¿Qué es la metrología? • El error en las mediciones • Sistema Métrico Legal Argentino (SIMELA) • Determinación del error • Definición de medición • Error relativo y error porcentual • Factores que afectan las mediciones • Medios de verificación y control • Instrumentos de medición y calibres • Conceptos de metrología • Diferencia entre medición y calibrado • Instrumentos de medición • Pie de Rey (Calibre) • Sondas o galgas de espesores • Micrómetro • Regla para control de planitud • Reloj comparador Módulo II • Motor naftero de cuatro tiempos • El mo', 'IMG-64ad84485df288.52976666.jpg', 1, '2023-07-01', '2023-10-23', 12, 7),
(21, 'SUSPENCIÓN Y DIRECCIÓN AUTOMOTOR', 5, ' DESTINATARIOS\r\n\r\n Destinado a personas que quieran aprender e iniciarse en el mundo de los sistemas que componen un automotor.  \r\n\r\nBJETIVOS Acercar los conocimientos básicos de los sistemas automotrices, así poder iniciar el camino a la capacitación de mayor nivel. Lograr insertarlos en el mundo laboral con conocimiento.  \r\n\r\nCONTENIDO  Módulo I Neumática e Hidráulica • Conceptos y magnitudes aplicadas a los fluidos • Preguntas para la evaluación diagnóstico • Concepto de fluido en los fluidos • Magnitudes y principios físicos de aplicación Circuitos neumáticos • Introducción • Características de los sistemas neumáticos • Propiedades físicas del aire • Principios físicos en gases • Producción de aire comprimido • Almacenamiento y tratamiento del aire comprimido Circuitos hidráulicos • Características de los circuitos hidráulicos • Elementos del circuito • Red de distribución Módulo II Sistemas de suspensión • Objetivo y funcionamiento de la suspensión • Preguntas para la evaluación d', 'IMG-64ad84d59dba65.33833415.jpg', 1, '2023-07-19', '2023-10-19', 24, 7),
(22, 'CORREAS Y TENSORES', 3, ' Historia\r\n-PRODUCTOS\r\n-CORREAS \r\n\r\nTipos en producción. \r\nDiagnóstico y roturas.\r\n\r\nTENSORES DE DISTRIBUCIÓN y POLY V.-KITS DE DISTRIBUCION. \r\nDiagnóstico y roturas Tensores', 'IMG-64ad863fc8f041.05702833.jpg', 3, '2023-07-20', '2023-07-20', 12, 4),
(23, 'LINEA TÉRMICA', 3, 'OBJETIVOS \r\nTransmitir los beneficios y propiedades de nuestros productos                                                                     \r\n\r\nCONTENIDO\r\n• Radiadores • Intercoolers • Radiadores de Aceite • Termostatos • Que son cada uno y sus fallas ', 'IMG-64ad8a46b9b410.97983744.jpg', 3, '2023-07-18', '2023-07-18', 24, 4),
(25, 'COJINETES', 3, 'OBJETIVOS\r\nTransmitir los beneficios y propiedades de nuestros productos                                                                     \r\n\r\nCONTENIDO\r\n• Línea pesada y liviana • Concepto de luces y ajustes • Nuevas Tecnologías de fabricación y prestaciones asociadas • Fallas típicas y causas que las producen • Influencia de la lubricación sintética ', 'IMG-64ad8b74ec09e0.53681711.jpg', 3, '2023-07-22', '2023-07-22', 10, 4),
(26, 'TURBOCOMPRESORES', 3, 'OBJETIVOS \r\nTransmitir los beneficios y propiedades de nuestros productos                                                                     \r\n\r\nCONTENIDO TURBOCOMPRESORES\r\n• Livianos y pesados • Tecnología de Fabricación y conceptos básicos de montaje en los vehículos • Fallas en los turbocompresores debido al uso • Lubricación e inyección ', 'IMG-64ad8bf1cb71f0.89702238.jpg', 3, '2023-07-22', '2023-07-22', 13, 4),
(27, 'JUNTAS', 3, 'OBJETIVOS \r\nTransmitir los beneficios y propiedades de nuestros productos                                                                     \r\n\r\nCONTENIDO \r\nJuntas de Culata • Tipos/Materiales • Propiedades y Características • Condición de la Superficie • Tipos de Fuga • Forma de Montaje Elementos de fijación y otros tipos de apriete Retenes/Tipos • Funcionamiento • Fallas potenciales ', 'IMG-64ad8c824710a7.28568364.jpg', 3, '2023-07-25', '2023-07-25', 12, 4),
(28, 'BUJIAS Y CABLES', 3, 'Temario: \r\n- Características y Codificación de\r\n- Bujías - Cables de Encendido - Bujías\r\n- STD - Resistivas - Green Pluss - De metales preciosos', 'IMG-64ad8d158defd6.24727511.png', 3, '2023-07-30', '2023-07-30', 11, 4),
(29, 'TURBOCOMPRESORES', 3, 'OBJETIVOS \r\nTransmitir los beneficios y propiedades de nuestros productos                                                                   \r\n\r\nCONTENIDO \r\n• Nivel 1 (inicial) • 1-El turboalimentador • 1-1-Justificación del uso del turboalimentador. • 1-2-Principio de funcionamiento. • 1-3-Componentes fundamentales. • 1-4-Identificación del turboalimentado. • 1-5-Ventajas del uso del turboalimentado. • 2-Fallas en los turboalimentadores por agentes externos • 2-1-Temperatura de gases de escape excesiva. • 2-2-Materiales extraños en la rueda compresora. • 2-3-Rueda compresora erosionada. • 2-4-Rueda compresora atacada por formaciones salitrosas. • 2-5-Materiales extraños en la rueda de turbina. • 2-6-Lubricación deficiente. • 2-7-Otras causas de falla. • 3-Cuidados del turboalimentado • 3-1-Aceite. • 3-2-Filtro de aceite. • 3-3-Filtro de aire. • 4-Instalación del turboalimentado • 4-1-Precauciones a verificar en el motor previo a la instalación de turbo alimentadores. • 4-2-Recomendacio', 'IMG-64ad8e2cce6d11.61759323.jpg', 3, '2023-07-12', '2023-07-12', 24, 4),
(30, 'CLIMATIZACION AUTOMOTRIZ', 1, 'DESTINATARIOS\r\nDestinado al personal que realice mantenimiento y reparaciones de A/A y quieran intervenir vehículos con climatización automática. Es necesario tener realizado el curso de A/A \r\n\r\nOBJETIVOS\r\n Tiene como objetivo interpretar el sistema en su funcionamiento reconocer sus componentes y diagnosticar correctamente. La climatización automotriz requiere componentes eléctricos y electrónicos, esto, nos obliga a medir, emular y diagnosticar cada uno de ellos. \r\n\r\nCONTENIDO Principios básicos del funcionamiento del aire acondicionado automotriz. Reconocimiento de un sistema climatizador. Como lo identificamos. Como actúa. Cómo reacciona. \r\nctura del sistema, explicación de cada uno de los módulos y forma de trabajo. • Sensores. • Actuadores. • Unidad de control. • Sensores NTC – PTC. • Sensores temperatura exterior. • Zonda térmico interior. • Temperatura aire central. • Sensores de humedad. • Captación solar. • Calidad y limpieza de aire. • Presostatos electrónicos. • Forzadores', 'IMG-64ad96396975d1.46595898.jpg', 2, '2023-08-01', '2023-08-03', 13, 5),
(31, 'MOTOS ALTA DE CILINDRADA', 1, 'DESTINATARIOS:\r\nEl siguiente curso va dirigido a talleristas con un conocimiento básico- previo, que quieran profundizar y desarrollar trabajos en motos de varios cilindros y alta complejidad. \r\n\r\nOBJETIVOS:\r\nLa finalidad de este curso será poder entender en profundidad e individualmente todo lo que respecta a la afinación de motos con características que requieran métodos de trabajo muy específicos y delicados.\r\n\r\nCONTENIDO:\r\n• Conocimiento específico y profundo de los distintos tipos de aceites a emplear. • Conocimiento de los distintos filtros; material, composición y • rendimiento. • Calibración y registro de los distintos sistemas de distribución. • Ajuste y calibración de múltiples carburadores. • Utilización de vacuómetro. • Chequeo y control mediante scanner de la inyección.', 'IMG-64ad96d2cb16a5.29797441.jpg', 2, '2023-07-05', '2023-07-08', 29, 5),
(32, 'MOTORIZACIÓN THP NIVEL 1', 1, 'CONTENIDOS: \r\nPresentación de los distintos tipos de motores • 120 cv / 156 cv / 165 cv / 200 cv • Conceptos básicos de inyección directa • Sistema Valvetronic • Sobrealimentación asistida electrónicamente Periféricos del Motor • Bomba de agua eléctrica y accionamiento intermediario de bomba eléctrica convencional • Bomba de aceite pilotada ', 'IMG-64ad97246777b4.45195559.jpg', 2, '2023-08-20', '2023-08-23', 26, 5),
(33, 'MOTORIZACIÓN THP NIVEL 2', 1, 'CONTENIDOS: \r\nPresentación de los distintos tipos de motores • 120 cv / 156 cv / 165 cv / 200 cv • Conceptos básicos de inyección directa • Sistema Valvetronic • Sobrealimentación asistida electrónicamente Periféricos del Motor • Bomba de agua eléctrica y accionamiento intermediario de bomba eléctrica convencional • Bomba de aceite pilotada ', 'IMG-64ad9742d1ced5.51136628.jpg', 2, '2023-08-24', '2023-08-27', 11, 7),
(34, 'MOTORIZACIÓN THP NIVEL 3', 1, 'FINALIDAD U OBJETIVOS DEL CURSO: \r\n-Una vez finalizado el curso los participantes podrán: •Realizar diagnóstico de manera precisa, certera y eficiente de los sistemas valvetronic presentes en las motorizaciones THP de más de 200 cv •Establecer a partir de la hipótesis de falla la secuencia correcta de actividades por realizar •Seleccionar y manipular con destreza y en forma segura las herramientas necesarias para los trabajos de reparación y diagnóstico. •Funcionamiento y control del sistema •Identificación de las distintas evoluciones del sistema •Identificación de los nuevos componentes de las evoluciones F y similares •Nueva inyección bosch', 'IMG-64ad977cdb5304.30758638.jpg', 2, '2023-08-29', '2023-09-01', 11, 4),
(35, 'MOTORES SISTEMAS DIESEL HDI', 1, 'CONTENIDOS:\r\nUna vez finalizado el curso los participantes podrán: • Lograr interpretar la correcta finalidad de los sistemas HDI • Se logra un entendimiento del sistema en su conjunto para poder abordar las fallas y llegar al diagnóstico correcto • Lograr la correcta medición de sensores y actuadores e identificar sus fallas • Diagnóstico de Inyectores, Medición eléctrica control por scanner, control por retornos', 'IMG-64ad988537d9a3.99526084.jpeg', 2, '2023-09-01', '2023-09-03', 24, 7),
(36, 'VEHÍCULOS ELECTRICOS NIVEL 1', 1, 'CONTENIDOS:\r\nUna vez finalizado el curso los participantes podrán: • Lograr interpretar la correcta finalidad de los sistemas HDI • Se logra un entendimiento del sistema en su conjunto para poder abordar las fallas y llegar al diagnóstico correcto • Lograr la correcta medición de sensores y actuadores e identificar sus fallas • Diagnóstico de Inyectores, Medición eléctrica control por scanner, control por retornos\r\n12) Sistema de almacenamiento de energía • Parámetros fundamentales de una batería de un EV • Concepto de una batería de EV • Tipos de celdas según su composición química • Tipos de celdas según su forma geométrica • Tecnologías más utilizadas en baterías de VE • Montaje de un pack de baterías • Módulo BMS (battery management system) • Sensor de corriente • Refrigeración del pack de baterías  • Elementos de protección necesarios 13) Proceso de carga de una celda de ion-litio 14) Sistema de recarga de un VE 15) Sistema de carga on board 16) Sistema de carga off board 17) Pre', 'IMG-64ad994f188ff8.36102666.jpg', 2, '2023-09-02', '2023-09-05', 11, 7),
(37, 'SOLDADURA EN ALUMINIO', 1, 'CONTENIDOS:\r\nUnidad 1 • Acondicionar los insumos y el espacio de trabajo y poner a punto el equipo de soldar interpretando la especificación de la orden de trabajo. 1.1 Interpretar las especificaciones orales, escritas o gráficas de la soldadura para planificar la secuencia de actividades a realizar. • 1.2 Acondicionar el espacio de trabajo aplicando criterios de seguridad e higiene establecidos por normas generales y particulares para prevenir riesgos y asegurar la calidad y productividad del proceso. • 1.3 Controlar las condiciones cuantitativas del material base a soldar.\r\nUnidad 2 • Proponer acciones de mejora continua del proceso de soldadura y del ámbito de trabajo. • 2.1 Redactar informes y completar registros que identifiquen mejoras a incorporar en el proceso y en el ámbito de trabajo, aplicando conceptos de productividad, calidad, orden, seguridad, higiene y preservación del medioambiente. Unidad 3 • Soldar, aplicando las técnicas del proceso de soldadura TIG en chapas de ac', 'IMG-64ad99c2db78c4.97035364.jpg', 2, '2023-09-02', '2023-09-05', 12, 5),
(38, 'VÁLVULAS', 3, 'CONTENIDO\r\n• Concepto de sistemas multiválvulas • Nuevas tecnologías en válvulas y asientos • Fallas del sistema de sellado de la cámara • Falla de válvulas    ', 'IMG-64ad9af33f2b88.95740255.jpg', 2, '2023-10-10', '2023-10-10', 12, 4),
(39, 'MECÁNICA DE MOTOS INICIAL', 5, 'OBJETIVOS\r\nAcercar los conocimientos básicos de la reparación de motos, así poder iniciar el camino a la capacitación de mayor nivel. Lograr insertarlos en el mundo laboral con conocimiento. \r\n\r\nCONTENIDO\r\n • Diagnóstico de fallas y reparación del motor y sus subsistemas • El proceso de diagnóstico • Función del orden de trabajo, Importancia de un buen diagnóstico. • Componentes y funcionamiento del motor • Ciclo de 4 tiempos • Ciclo de 2 tiempos. • Sistema de distribución. • Factores que provocan fallas en el mismo. • Conocimiento y correcta utilización de las herramientas de medición • Sonda • Micrómetro • Calibre • Manómetro • Compresómetro • Torquímetro. • Manejo de herramientas de modo seguro. • Manejo e interpretación de tablas de especificaciones técnicas. • Problemas en aros, pistón y cilindros. • Medición de luz entre el cilindro y el pistón. • Función y relación entre cigüeñal, árbol de levas, cojinetes y rodamientos. • Control de desgaste y reparación referida a la medición ', 'IMG-64ad9b8fa955f0.03373739.jpg', 1, '2023-07-04', '2023-10-04', 28, 7),
(40, 'CHAPERIA Y PINTURA AUTOMOTOR', 5, 'CONTENIDO\r\n• 1. Introducción a la Chapería. • 2. Recepción del vehículo, reparación de los daños. • 3. Tipos de herramientas que conoce para la reparación de un vehículo. • 4. Pasos que seguir para reparar el capot, puerta, etc. De un vehículo. • 5. Los diferentes métodos para soldar la chapa • 6. Elementos de seguridad. • 7. Máquina saca bollos: funcionamiento y características. • 8. Equipo Autógeno: elementos de este. • 9. Como realizar el encendido del equipo autógeno. • 10. Soldadura Mig y sus elementos de seguridad. • 11. Cuidados que hay que tener en el momento de desarmar un vehículo. • 12. Equipo expansor. • 13. Banco chapista. • 14. Evaluación final ', 'IMG-64ad9c27861418.61328272.jpg', 2, '2023-09-20', '2023-12-20', 24, 4),
(41, 'MEDICIÓN SENSORES Y ACTUADORES', 5, 'OBJETIVOS\r\nAcercar los conocimientos básicos del funcionamiento de los sensores y actuadores, así poder iniciar el camino a la capacitación de mayor nivel. Lograr insertarlos en el mundo laboral con conocimiento.  \r\n\r\nCONTENIDO\r\nMódulo I Sistemas de alimentación en motores Otto • Combustible y características de la mezcla • Características de la mezcla • Gasolina • Elementos comunes a todo sistema de alimentación • Depósito de combustible • Filtro de aire • Bomba de combustible • Tuberías  Módulo II Sistemas de inyección electrónica • Sistemas de alimentación en motores de gasolina • Preguntas para la evaluación diagnóstica • Tipos de corriente en los sistemas de gestión • Clasificación de los sistemas de inyección electrónica • Unidad de control electrónica (ECU) 2.5 Verificación de las caídas de tensión • Sistemas de inyección • Inyección mono punto • Inyección multipunto directa • Inyección multipunto indirecta • Funcionamiento básico de los sistemas de inyección multipunto.', 'IMG-64ad9d4043e444.18347343.jpg', 2, '2023-01-02', '2023-04-02', 11, 5),
(42, 'GESTION DE TALLER', 2, 'OBJETIVOS\r\n• Desarrollar método y actividades para lograr mejorar la gestión administrativa y técnica del negocio, en relación con el contexto actual y lograr que nuestros clientes repitan en el servicio y poder captar nuevos clientes.\r\n\r\nCONTENIDO\r\n• Realizar un ingreso y diagnóstico adecuado como base de lograr una reparación y servicio que satisfaga al cliente • Realización de un presupuesto jurídicamente correcto • Involucramiento de los colaboradores con una permanente capacitación • Adecuación del flujo de tareas para optimizar los tiempos, los recursos, reducir costos y maximizar la rentabilidad.\r\n• Adecuación del tratamiento de los repuestos y las evoluciones de esos costos • Evaluar y accionar sobre los riesgos potenciales del negocio • Prestar un servicio de excelencia para que nuestros clientes repitan y captar nuevos clientes. \r\n\r\nREQUISITOS DE INGRESO\r\n• Poseer experiencia en el trabajo en servicios automotor o estar comenzando esta actividad.', 'IMG-64ad9e34d62870.45022189.jpg', 2, '2023-10-02', '2023-10-05', 28, 4),
(43, 'MARKETING INICIAL', 2, 'OBJETIVOS Ingresar al mundo de la promoción digital de nuestros productos/trabajos, accediendo al conocimiento de las herramientas disponibles. \r\n\r\nCONTENIDO • Conocimientos generales de marketing para principiantes • Marketing digital • Herramientas.  \r\n\r\nREQUISITOS DE INGRESO • Conocimientos de manejo de herramientas informáticas y secundario completo.', 'IMG-64ad9e98720d87.69151438.jpg', 2, '2023-10-17', '2023-10-17', 13, 4),
(44, 'MEJORAS DE PROCESO', 2, 'OBJETIVOS\r\nObtener los conocimientos necesarios para la optimización de los procesos y mejoras en la gestión con sus clientes. \r\n\r\nCONTENIDO \r\n✓Enfoque a procesos. ✓Qué hacemos, como lo hacemos, análisis de actividades claves. ✓Que actividades suman valor al cliente y cuáles no. ✓Enfoque 360° del negocio y sus procesos', 'IMG-64ad9f834834a1.64837412.jpg', 2, '2023-11-01', '2023-11-04', 29, 5),
(45, 'S&H PARA TALLER', 2, 'A QUIEN ESTA DIRIGIDO:\r\n- Titulares de Talleres o administrativos   \r\n\r\nFINALIDAD U OBJETIVOS DEL CURSO: \r\n- Una vez finalizado el curso los participantes podrán: • Conocer la legislación vigente en materia de Higiene y Seguridad • Comprender los beneficios de aplicar las normas de Higiene y Seguridad en su taller • Aprender cómo evitar multas, suspensiones o clausuras • Aplicar técnicas de orden y limpieza en su lugar de trabajo • Preparar sus establecimientos para la prevención de incendios • Realizar una correcta gestión de los residuos que genera el taller • Manipular y almacenar productos químicos de forma segura • Aplicar los protocolos de bioseguridad para la prevención de COVID-19 • Como seleccionar elementos de protección.\r\n\r\nCONTENIDOS: \r\nIntroducción a la Higiene y Seguridad • Para qué sirve la higiene y seguridad • Beneficios de aplicar normas de higiene y seguridad en su taller • Como evitar multas • Marco Legal • Análisis de la legislación • La importancia del orden y la', 'IMG-64ada145e512e5.99956815.jpg', 2, '2023-10-22', '2023-10-25', 11, 7),
(46, 'S&H PARA OPERARIOS', 2, 'DESTINATARIOS\r\nEmpleados de talleres y titulares sin empleados \r\n\r\nOBJETIVOS \r\n• Comprender para que sirve la higiene y seguridad • Identificar actos y condiciones inseguras en su puesto de trabajo • Prevenir accidentes laborarles • Distinguir las señales y colores de seguridad • Evitar contactos eléctricos • Utilizar un matafuego • Aprender a actuar en casos de emergencia • Utilizar de forma correcta y cuidar los elementos de seguridad • Separar las distintas clases de residuos que genera el taller • Conocer las técnicas adecuadas para el manejo manual de cargas pesadas • Manipular y almacenar productos químicos de forma segura • Aplicar los protocolos de bioseguridad para la prevención del • covid-19 \r\n\r\nCONTENIDO\r\n• Introducción a la higiene y seguridad - ¿Para sirve la higiene y seguridad? - Distinguir accidentes de incidentes - Detectar actos y condiciones inseguras • La importancia de mantener su lugar de trabajo limpio y ordenado - Significado de los colores de seguridad - Signi', 'IMG-64ada1fd582398.67648301.jpg', 2, '2023-11-01', '2023-11-04', 29, 7),
(47, 'GESTION RR.HH', 2, 'DESTINATARIOS \r\n• Titulares de talleres, administrativos o encargados \r\n\r\nOBJETIVOS • Obtener los conocimientos necesarios para la gestión de los recursos humanos de su empresa \r\n\r\nCONTENIDO • Conceptos generales de RRHH. • Gestión de RRHH herramientas. • La Inteligencia Colaborativa para el progreso y sustentabilidad de las empresas Pymes. • La mejora continua y sus beneficios. \r\n\r\nREQUISITOS DE INGRESO\r\n• Conocimientos de manejo de herramientas informáticas y secundario completo.', 'IMG-64ada258e7a988.84898279.jpeg', 2, '2023-11-10', '2023-11-13', 24, 5),
(48, 'ANALISIS DE COSTO', 2, 'DESTINATARIOS \r\n\r\nDestinado a titulares o administrativos de talleres\r\n\r\nOBJETIVOS\r\n • Mejorar la toma de decisiones a partir de un profundo conocimiento de los costos de la empresa. • Comprender la importancia del Punto de Equilibro Dinámico del negocio para minimizar pérdidas en época de crisis • Conocer con precisión la importancia de tomar decisiones agiles pensando en la supervivencia de mi negocio. • Lograr un aprendizaje que permita enfrentar la próxima crisis con más herramientas.', 'IMG-64ada2c27ed841.64059673.jpeg', 2, '2023-11-18', '2023-11-21', 28, 4),
(52, 'FECHACO', 5, ' es una prueba 1111', '', 0, '2023-10-10', '2023-10-10', 0, 0);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `cursos`
--
ALTER TABLE `cursos`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id_capacitador` (`id_capacitador`),
  ADD KEY `id_modalidad` (`id_modalidad`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `cursos`
--
ALTER TABLE `cursos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
